[FEAT] 도서 API 데이터 요청 및 저장 기능 구현
Moongeul/Backend pull request #19
Opened 2024-08-16 06:51 UTC by gogori6565

## 📣 Related Issue

- close #14 

## 📝 Summary

네이버 도서 API 를 활용해 도서 데이터 요청 및 저장 기능을 구현했습니다.

## 🙏 Question & PR point

- 도서 데이터 요청(검색) 및 저장 기능 엔드포인트 : {URL}/api/v1/book
- 네이버 도서 API는 '카테고리' 정보를 일체 반환하지 않습니다.
- 검색 시 일부 도서의 외국어 정보를 걸러내는 방법을 찾아야 할 것 같습니다.
- Q. BookController.java 파일에 ApiResponse 를 통한 응답 요청 반환 코드 부분에 ApiResponse 클래스가 제네릭 타입을 사용하지 않았다는 경고 메시지가 출력됩니다.

## 📬 Reference

![image](https://github.com/user-attachments/assets/3031952f-b553-46d3-8ec9-e91f2f14d5b4)

2024-08-17 22:37 UTC, rhkr8521 approved these changes
고생하셨습니다!

2024-08-18 23:29 UTC, rhkr8521 requested changes

2024-08-18 23:29 UTC, rhkr8521 commented on src/main/java/com/core/book/api/book/entity/Book.java
> +//    @Column
image, link, discount, isbn이 ERD와 다릅니다, 처음 설계 당시 isbn이 pk로 가기로했던거 같은데 바꾸신 이유가 있으실까요?

2024-08-19 06:47 UTC, gogori6565 commented on src/main/java/com/core/book/api/book/entity/Book.java
> +//    @Column
link, discount, isbn은 DB에 저장되지 않도록 수정하였습니다.

2024-08-20 01:43 UTC, rhkr8521 approved these changes
고생하셨습니다~!

2024-08-20 06:53 UTC, merged